### ISSUE TITLE
1.3.5.5 - NotFoundException: getDirt

### ISSUE THREAD

**Issue by ghost** [bdew-wurm/betterdig#1]
Since the 1.3.5.5 update, BetterDig is preventing the WU server from starting (included error).
[BetterDigError.txt](https://github.com/bdew-wurm/betterdig/files/990458/BetterDigError.txt)

**Comment by DiWorm** [comment]
Some issue, server dont start after 1.3.5.5

**Comment by bdew** [comment]
New version up -https://github.com/bdew-wurm/betterdig/releases/tag/v0.5
